# Generated by Django 2.1.3 on 2018-11-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.CharField(choices=[('ES', 'Wieczna Walka'), ('BOTB', 'Księgarnia ksiąg prawdziwych'), ('NS', 'Bez serii')], default='NS', max_length=4),
        ),
    ]
