# Generated by Django 2.1.3 on 2018-11-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('volume_nr', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Series'),
        ),
    ]
