# Generated by Django 2.1.3 on 2018-11-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181123_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chapter_nr',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
