# Generated by Django 2.1.3 on 2018-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181123_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='volume_nr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
