# Generated by Django 2.1.2 on 2018-11-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181123_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='series',
            new_name='book',
        ),
    ]

    atomic = False